apiVersion: apps/v1
kind: Deployment
metadata:
  name: meetup-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meetup-demo
  template:
    spec:
      containers:
      - name: meetup-demo
        image: eu.gcr.io/dev-ops-meetup/meetup-demo:0.0.1
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_OPTS
          value: "-Xmx1024m -Xms256m"
        - name: SPECIAL_LEVEL_VAL
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: SPECIAL_LEVEL